MovieApp/config/routes.rb
Rails.application.routes.draw do
  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie
  get '/actors' => 'actors#index'
  get '/actors/:id' => 'actors#show', as: :actor
end

MovieApp/app/models/actor.rb
class Actor < ActiveRecord::Base
has_many :parts 
has_many :movies, through: :parts
	
end

MovieApp/app/models/movie.rb
class Movie < ActiveRecord::Base

has_many :parts 
has_many :actors, through: :parts
end

MovieApp/app/models/part.rb
class Part < ActiveRecord::Base
belongs_to :movie 
belongs_to :actor
end

MovieApp/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
	def index
		@actors = Actor.all
	end
	
	def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

MovieApp/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	
  def index
  	# @disable_nav = true
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
	
end

MovieApp/app/helpers/actors_helper.rb
module ActorsHelper
end

MovieApp/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieApp/app/views/actors/index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row">
          <% @actors.each do |actor| %>
          <div class="actor col-xs-2 actorHome">
            <%= image_tag actor.image %>
            <h3><%= actor.first_name + " " + actor.last_name %></h3>
            <%= link_to "Learn more", actor_path(actor) %>
          </div>
          <% end %>
        </div>
      </div>
</div>

MovieApp/app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="actor">
      <%= image_tag @actor.image %>
      <div class="info">
        <h3 class="actor-name"><%= @actor.first_name + " " + @actor.last_name  %></h3>
        <p class="actor-bio"><%= @actor.bio %></p>
        </br>
        <%= link_to "Back", actors_path() %>
      </div>
    </div>

    <h2>Movies</h2>
    <% @movies.each do |movie| %>
    <div class="movie">
      <%= image_tag movie.image %>
      <h3 class="movie-title"><%= movie.title %></h3>
      <p class="movie-release-year"><%= movie.release_year %></p>
      <p class="movie-plot"><%= movie.plot %></p>
    </div>
    <% end %>

  </div>
</div>

MovieApp/app/views/layouts/_navBar.html.erb
<div id="mySidenav" class="sidenav">
  <a href=<%= movies_path()%> id="about">Movies</a>
  <a href=<%= actors_path()%> id="blog">Actors</a>
  <a href="#" id="projects">About</a>
  <a href="#" id="contact">Login</a>
</div>

MovieApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navBar'%>
<%= yield %>

</body>
</html>

MovieApp/app/views/movies/index.html.erb
<div class="hero">
<!-- <%= render 'layouts/navBar' %> -->
  <div class="container">
    <h2>Interstellar</h2>
    <p>Former NASA pilot Cooper (Matthew McConaughey) and a team of researchers travel across the galaxy to find out which of three planets could be mankind's new home.</p>
    <a href="#">Read More</a>
  </div>
</div>

<div class="main">
  <div class="container">
  <h2>Popular Films</h2>
    <% @movies.each do |movie| %>
    <div class="movie movieHome">
      <%= image_tag movie.image %>
      <h3><%= movie.title %></h3>
      <p><%= movie.release_year %></p>
      <p><%= movie.plot %></p>
      <%= link_to "Learn more", movie_path(movie) %>
    </div>
    <% end %>
  </div>
</div>

MovieApp/app/views/movies/show.html.erb
<div class="main movie-show">
  <div class="container">
    <div class="movie">
      <!-- Display the movie's info here -->
      <%= image_tag @movie.image %>
      <div class="info">
        <h3 class="movie-title"><%= @movie.title %></h3>
        <p class="movie-release-year"><%= @movie.release_year %></p>
        <p class="movie-plot"><%= @movie.plot %></p>
        </br>
        <%= link_to "Back", movies_path() %>
      </div>
    </div>
    
    <h2>Cast</h2>
    <% @actors.each do |actor| %>
    <div class="actor">
      <%= image_tag actor.image %>
      <h3 class="actor-name"><%= actor.first_name %> <%= actor.last_name %></h3>
      <p class="actor-bio"><%= actor.bio %></p>
    </div>
		<% end %>
  </div>
</div>