TechLadies/EventMgt/config/routes.rb
Rails.application.routes.draw do
  resources :event
  
  root 'event#home'
  
  get 'eventz' => "event#home", as: :home 
  get 'eventz/contact' => "event#contact", as: :contact 
  get 'eventz/list' => "event#index", as: :index

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

TechLadies/EventMgt/app/models/event.rb
class Event < ActiveRecord::Base
  
  validates :title, :description, :presence=> true	
  validates :title, :uniqueness => {:message => "already exists!"}
	validate :validate_date 
  validate :image_available
  
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>", :normal => "400x700>" }
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

	def validate_date
		if date < Time.new
			errors.add(:date, "can't be in the past")
		end
	end  
  
  def image_available
    errors.add(:base, 'Please upload an image related to the event') if !image.present?
  end

  def self.search(search)
    if search
      where('LOWER(title) LIKE  ?', "%#{search}%")
    else
      all
    end
  end
  
end

TechLadies/EventMgt/app/models/user.rb
class User < ActiveRecord::Base

has_secure_password
	
end

TechLadies/EventMgt/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

TechLadies/EventMgt/app/controllers/event_controller.rb
class EventController < ApplicationController
  before_action :find_id, only: [:edit, :update, :destroy, :show]
  before_filter :authorize, only: [:index]
   
  def home
    @events = Event.all.sort_by &:date 
    if params[:search]
      @events = Event.search(params[:search])
    end
  end

  def contact
  end
  
  def show
    find_id 
  end
  
  def index
    @events = Event.all.sort_by &:date
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = "Record successfully created"
      redirect_to :action => 'index'
    else
      render :action => "new"
    end
  end
  
  def edit
    find_id
  end
  
  def update
    find_id
    if @event.update(event_params)
      flash[:success] = "Record successfully updated"
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    find_id
    @event.destroy
    flash[:success] = "Record successfully deleted"
    redirect_to :action => 'index' 
  end
  
  private
  
  def find_id
    @event = Event.find(params[:id])
  end
  
  def event_params
    params.require(:event).permit(:title, :description, :image, :date)
  end

end

TechLadies/EventMgt/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to event_index_path
    else
      flash[:danger] = "User Name/Password incorrect. Please re-try!"
      redirect_to '/login' 
    end
  end

  def destroy
  	session[:user_id] = nil
    flash[:success] = "You have logged out successfully!"
    redirect_to '/login'
  end

end

TechLadies/EventMgt/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
    end

    def create
    	user = User.new(user_params)
    	if user.save
    		session[:user_id] = user.id
    		redirect_to '/'
    	else
    		redirect_to '/signup'
    	end
    end 

    private

	def user_params
	  params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

TechLadies/EventMgt/app/helpers/events_helper.rb
module EventsHelper
end

TechLadies/EventMgt/app/helpers/sessions_helper.rb
module SessionsHelper
end

TechLadies/EventMgt/app/helpers/users_helper.rb
module UsersHelper
end

TechLadies/EventMgt/app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
      <% if current_user %>
         <%= link_to image_tag("/assets/logo-admin.png"), home_path%>
      <% else %>
         <%= link_to image_tag("/assets/logo.png"), home_path%>
      <% end %> 
      </div>
    </div>

    <div class="pull-left user-name">
        <% if current_user %>
          <span class="label label-primary">Signed in as <%= current_user.name %></span>
       <% end %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
           <li><%= link_to "Event Management", index_path %></li>
           <li><%= link_to "Logout", logout_path %></li> 
        <% else %>
           <li><%= link_to "Home", home_path %></li>
           <li><%= link_to "Contact Us", contact_path %></li>
           <li><%= link_to 'Login', login_path %> </li>
        <% end %>
      </ul>

      <div class="pull-right">
        <%= form_tag(home_path, :method => "get", :class => "navbar-form") do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Event", class: 'form-control' %>
              <div class="input-group-btn">
                <%= button_tag(type: "submit", class: "btn btn-default") do %>
                    <i class="fa fa-search" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to(home_path, :class=> 'btn btn-default') do %>
                    <i class="fa fa-times" aria-hidden="true"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

TechLadies/EventMgt/app/views/common/_slider.html.erb
<header id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for Slides -->
  <div class="carousel-inner">
    <div class="item active">
      <!-- Set the first background image using inline CSS below. -->
      <div class="fill" style="background-image:url('/assets/slider3.jpg');"></div>
      <div class="carousel-caption">
        <%#*<h2>Caption 1</h2>%>
      </div>
    </div>
    <div class="item">
      <!-- Set the second background image using inline CSS below. -->
      <div class="fill" style="background-image:url('/assets/slider1.jpg');"></div>
      <div class="carousel-caption">
        <%#*<h2>Caption 2</h2>%>
      </div>
    </div>
    <div class="item">
      <!-- Set the third background image using inline CSS below. -->
      <div class="fill" style="background-image:url('/assets/slider2.jpg');"></div>
      <div class="carousel-caption">
        <%#*<h2>Caption 3</h2>%>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="icon-next"></span>
  </a>

</header>

TechLadies/EventMgt/app/views/event/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 text-center">
      <h1 class="section-heading"><span class="label label-header">Let's Get In Touch!</span></h1>
      <hr class="primary">
      <p>Ready to launch your next event with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
    </div>
    <div class="col-lg-4 col-lg-offset-2 text-center">
      <i class="fa fa-phone fa-3x sr-contact"></i>
      <p>123-456-6789</p>
    </div>
    <div class="col-lg-4 text-center">
      <i class="fa fa-envelope-o fa-3x sr-contact"></i>
      <p><a href="mailto:eventz@gmail.com">feedback@gmail.com</a></p>
    </div>
    <div class="col-lg-10 col-lg-offset-1 text-center">
      <ul class="list-inline">
        <li>
          <a href="#"><i class="fa fa-facebook fa-fw fa-2x"></i></a>
        </li>
        <li>
          <a href="#"><i class="fa fa-twitter fa-fw fa-2x"></i></a>
        </li>
        <li>
          <a href="#"><i class="fa fa-dribbble fa-fw fa-2x"></i></a>
        </li>
      </ul>
      <hr class="small">
      <p class="text-muted">Copyright &copy; Eventz.sg 2016</p>
    </div>
  </div>
</div>

TechLadies/EventMgt/app/views/event/edit.html.erb
<div class="container">
</br>
<div class="rounded-border">
<h3>UPDATE EVENT</h3>
  <%= form_for @event, :url =>{:action => "update", :id =>@event}, html: { multipart: true} do |f| %>
  <%if @event.errors.any? %>
  <div class="alert alert-danger">
    <strong>Incorrect data entry :</strong>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
      <p>- <%= msg %></p>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter event title"%>
  </div> 

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', placeholder: "Enter event details"%>
  </div> 

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'btn btn-default btn-file'%>
  </div> 

  <div class="form-group">
    <%= f.label :event_date %></br>
    <%= f.datetime_select :date, {:ampm => true, :minute_step => 15}, {:order => [:day, :month, :year],  start_year: Date.today.year, end_year: Date.today.year + 2 }%>
  </div> 
  <%= f.submit 'Update event', :class=> 'btn btn-info' %>
  <%= link_to "Back", index_path, :class=> 'btn btn-info' %>
  <% end %>
</div>
</div>
</br>

TechLadies/EventMgt/app/views/event/home.html.erb
<!-- Page Content -->
<%  require 'time_diff' %>
<div class="container">

  <!-- Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <%if (@events.size != 0)%>
      <h1 class="page-header"><span class="label label-header">Upcoming Events</span> </h1>
    </div>
  </div>
  <!-- /.row -->

  <!-- Projects Row -->
  <div class="row">
    <% @events.each do |c| %>
    <%
      current_date = Time.now.strftime('%Y-%m-%d')
      event_date = c.date.strftime('%Y-%m-%d')
      countdown = Time.diff(Time.parse(current_date),Time.parse(event_date), '%y, %M, %d')
      current_time = Time.now.strftime('%Y-%m-%d %H:%M')
      event_time = c.date.strftime('%Y-%m-%d %H:%M')
    %>
    <!-- lists events which are not expired --> 
    <%if event_date >= current_date%>
    <div class="col-md-4 portfolio-item">
      <h4><strong><%= link_to c.title, event_path(:id=>c.id) %></strong></h4>
      <h4><p class="count-down">
        <!--if event time is less than the current time, event will be categorized as expired and will be removed from the list on the following day-->
        <%if event_date == current_date%>
          <%if (current_time > event_time)%>
             <span class="label label-danger">Event Expired!!!</span>
          <% else %>
             <%  hours_left = Time.diff(Time.parse(current_time),Time.parse(event_time), '%y, %M, %d %H %N')%>
             <div class="hour-count-blink"><%= hours_left[:diff] +" left"%> &nbsp;&nbsp;<span class="label label-danger">Expiring Soon!!!</span></div>
          <% end %>
    <% else %>
    <%= countdown[:diff] + " left"%>
    <% end %>
    </p></h4>
    <ul class="demo-3">
      <li>
        <figure>
          <%= image_tag c.image.url(:medium), :class=>"img-responsive" %>
          <figcaption>
            <p><font size="3"><%= truncate(c.description, :length => 175 ) { link_to "Continue", event_path(:id=>c.id) } %></font></p>
          </figcaption>
        </figure>
      </li>
    </ul>
  </br>
</div>
<% end %>
<% end %>
</br>
</div>
<hr>
<% else %>
</br>
<div class="alert alert-danger">
  <strong>Sorry...no result found for the search key word <i>'<%= params[:search] %>'</i></strong>
</div>
<% end %>
</div>

<script type="text/javascript"> 
  
  $(document).ready(function(){
    function blinker() {
      $('.hour-count-blink').fadeOut(500);
      $('.hour-count-blink').fadeIn(500);
    }
      setInterval(blinker, 1000);
  });

</script>

TechLadies/EventMgt/app/views/event/index.html.erb
<div class="container">
  <h2></h2>
  <table class="table table-hover">
    <%= link_to "Add New Event", new_event_path, :class=> 'btn btn-info btn_add_new' %>
    <thead>
      <tr>
      <th>Event</th>
      <th>Description</th>
      <th>Date</th>
      <th>Time</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
       <% @events.each do |c| %>
      <tr>
      <%
        current_date = Time.now.strftime('%Y-%m-%d')
        event_date = c.date.strftime('%Y-%m-%d')
        is_expired = false
        if event_date < current_date
          is_expired = true
        end
      %>
        <td class="col-md-2"><%= c.title %> <%if is_expired%><span class="label label-danger">EXPIRED!!!</span><%end%></td>
        <td class="col-md-6"><%= c.description %></td>
        <td><%= c.date.strftime("%Y-%m-%d") %></td>
        <td><%= c.date.strftime("%H:%M %p") %></td>
        <td><%= image_tag c.image.url(:thumb) %></td>
        <td><%= link_to edit_event_path(c), title: 'Update', 'data-toggle' => 'tooltip', 'data-placement' => 'right' do%><i class="fa fa-pencil-square-o fa-lg"></i><%end%></td>
        <td><%= link_to event_path(:id=>c.id), method: :delete, data: { confirm: 'Are you sure to delete the record?' }, title: 'Delete', 'data-toggle' => 'tooltip', 'data-placement' => 'right'  do%><i class="fa fa-trash fa-lg"></i><%end%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

TechLadies/EventMgt/app/views/event/new.html.erb
<div class="container">
</br>
  <div class="rounded-border">
  <h3>CREATE AN EVENT</h3>
  <%= form_for @event, :url =>{:action => "create", :id =>@event}, html: { multipart: true} do |f| %>
    <%if @event.errors.any? %>
      <div class="alert alert-danger">
        <strong>Incorrect data entry :</strong>
        <ul>
            <% @event.errors.full_messages.each do |msg| %>
              <p>- <%= msg %></p>
            <% end %>
          </ul>
      </div>
    <% end %>
    
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter event title"%>
    </div> 
      
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', placeholder: "Enter event details"%>
    </div> 
      
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: 'btn btn-default btn-file'%>
    </div> 
      
      <div class="form-group">
      <%= f.label :event_date %></br>
      <%= f.datetime_select :date, {:ampm => true, :minute_step => 15}, {:order => [:day, :month, :year],  :start_year=> Time.now.year, :end_year=> Time.now.year + 2 }%>
      </div> 
        <%= f.submit 'Create Event', :class=> 'btn btn-info' %>
        <%= link_to "Back", index_path, :class=> 'btn btn-info' %>
    <% end %>
    </div>
  </div>
</br>

TechLadies/EventMgt/app/views/event/show.html.erb
</br>
<div class="container">
  <div class="panel-group">
    <div class="panel panel-info">
      <div class="panel-heading"><h4><%= @event.title %></h4></div>
      <div class="panel-body">
        <div class="section1" style="float:left; width: 65%;">
          <b>Event Details : </b> 
          <pre><%= @event.description %></pre>
          <b>Date :</b> </br><%= @event.date.strftime("%Y-%m-%d") %></br>
          <b>Time :</b> </br><%= @event.date.strftime("%H:%M %p") %>
          </br></br></br></br>
          <%= link_to "Back", home_path, :class=> 'btn btn-default' %>
        </div>
        <div class="section2" style="float:right; width: 35%;">
          <%= image_tag @event.image.url(:medium) %>
        </div>
      </div>
    </div>
  </div>
</div>

TechLadies/EventMgt/app/views/layouts/_flash_msg.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

TechLadies/EventMgt/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventz : Your one stop events shop!</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="/assets/jquery.min.js"></script>
   <%= csrf_meta_tags %>
</head>
<body>
<%= render 'common/navbar' %>
<%= render 'common/slider' %>
<%= render "layouts/flash_msg" %>
<%= yield %>
</body>
</html>

TechLadies/EventMgt/app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>